name: Eleventy Build & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci || npm install || true

      - name: Build (Eleventy)
        run: |
          if [ -f package.json ] && jq -e '.scripts.build' package.json > /dev/null 2>&1; then
            npm run build
          else
            npx @11ty/eleventy
          fi

      - name: Add .nojekyll
        run: touch _site/.nojekyll

      - name: Ensure root index.html
        run: |
          mkdir -p _site
          if [ ! -f "_site/index.html" ]; then
            echo '<!doctype html>' > _site/index.html
            echo '<html>' >> _site/index.html
            echo '  <head>' >> _site/index.html
            echo '    <meta charset="utf-8">' >> _site/index.html
            echo '    <title>Het Rajesh Nagda — MSCS @ UIC</title>' >> _site/index.html
            echo '    <meta http-equiv="refresh" content="0; url=./home/">' >> _site/index.html
            echo '    <link rel="canonical" href="./home/">' >> _site/index.html
            echo '  </head>' >> _site/index.html
            echo '  <body>' >> _site/index.html
            echo '    <p>Redirecting to <a href="./home/">home</a>…</p>' >> _site/index.html
            echo '  </body>' >> _site/index.html
            echo '</html>' >> _site/index.html
          fi

      - name: Show _site contents
        run: |
          echo "=== _site (top-level) ==="
          find _site -maxdepth 2 -type f -print

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
