name: Eleventy Build & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps (ok if none)
        run: npm install || true

      - name: Build site
        run: npx @11ty/eleventy

      # Add a root index if your Eleventy build didn't create one.
      # If you already have index.html in source and Eleventy copies it, this step is harmless.
      - name: Ensure root index.html redirects to /home/
        run: |
          mkdir -p _site
          if [ ! -f "_site/index.html" ]; then
            cat > _site/index.html <<'HTML'
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Het Rajesh Nagda — MSCS @ UIC</title>
    <meta http-equiv="refresh" content="0; url=./home/">
    <link rel="canonical" href="./home/">
  </head>
  <body>
    <p>Redirecting to <a href="./home/">home</a>…</p>
  </body>
</html>
HTML
          fi

      - name: Add .nojekyll
        run: touch _site/.nojekyll

      - name: Show what will be deployed (debug)
        run: |
          echo "=== _site contents ==="
          find _site -maxdepth 2 -type f -print

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
